fix: hot reload didn't work property
mkobuolys/flutter_deck pull request #61
Opened 2024-02-21 18:14 UTC by tomcheung

## Description

Fixed hot reload didn't work proprety when running in macOS desktop mode

This is due to behaviour change in go_router start from 13.0, go_router `pageBuilder` no longer called after hot reload, that mean `slide.widget.build(context)` will only call once on init state, and cause `FlutterDeckSlideWidget.build` will not call again to reflect the change (like change the title in `FlutterDeckSlide.title(title: 'xxx')`)

https://github.com/mkobuolys/flutter_deck/blob/e68f538121dd8a680aeb3e1b35131647357298b2/lib/src/flutter_deck_router.dart#L62-L66

Do fix this issue, this PR will move `slide.widget.build(context)` to a wrapper widget so it will trigger when hot reload is performed

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-02-21 18:18 UTC, tomcheung commented on lib/src/flutter_deck_app.dart
> +    _router = _flutterDeckRouter.build();
@mkobuolys look like just call build `_flutterDeckRouter.build()` works, so i didn't call `_buildRouter()` to rebuild the entiry router, do you think it still need to call `_buildRouter()`?

2024-02-22 23:35 UTC, mkobuolys commented on lib/src/flutter_deck_router.dart
> +              child: _FlutterDeckSlidePage(slide),
No need for any custom widgets, the simple `Builder` should do the trick:

```suggestion
              child: Builder(builder: slide.widget.build),
```

2024-02-22 23:38 UTC, mkobuolys requested changes
Good catch, thank you! Also, please, add release notes at the top of the `CHANGELOG.md` file, like:

```
# NEXT

fix: hot reload doesn't work on MacOS
```

2024-02-23 11:46 UTC, tomcheung commented
Thanks for suggestion, updated in [66ebc7e](https://github.com/mkobuolys/flutter_deck/pull/61/commits/66ebc7e6fc0316ab48c4003075fa9ccbea7b82bf)

2024-02-23 12:00 UTC, mkobuolys approved these changes
Thanks for your contribution!

2024-02-23 12:00 UTC, merged