Added support for localization
mkobuolys/flutter_deck pull request #62
Opened 2024-03-02 11:56 UTC by chooyan-eng

## Status

**READY**

## Description

Added support for localization of slides by bypassing `MaterialApp`'s parameters for localization.

This would be useful for those (like me) who originally made a slide in a non-English language, Japanese for instance, and want to share it globally with the same URL.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-03-02 21:34 UTC, mkobuolys commented on lib/src/flutter_deck_app.dart
> +  /// The initial locale for the slide.
```suggestion
  /// The initial locale for the slide deck.
```

2024-03-02 21:34 UTC, mkobuolys commented on lib/src/flutter_deck_app.dart
> +  /// The delegates for the slide's localization.
```suggestion
  /// The delegates for the slide deck's localization.
```

2024-03-02 21:34 UTC, mkobuolys commented on lib/src/flutter_deck_app.dart
> +  /// The list of locales that the slide has been localized for.
```suggestion
  /// The list of locales that the slide deck has been localized for.
```

2024-03-02 21:37 UTC, mkobuolys requested changes
Thanks for the contribution! Just some minor adjustments to documentation are needed.
Also, do not forget to update the `CHANGELOG.md` file, like:

```
# Next

- feat: add support for slide deck localization
```

2024-03-03 02:37 UTC, chooyan-eng commented
@mkobuolys Thank you for reviewing! I've fixed both of them.

2024-03-03 10:41 UTC, mkobuolys approved these changes
Looking good! Today I will try to add a control to change the slide deck's language at run-time, update the docs, and example. It will be released with v0.12.0 ASAP.

2024-03-03 10:41 UTC, merged

2024-03-03 21:54 UTC, chooyan-eng commented
@mkobuolys Big appreciation for merging! I'll use this when released as I have one slide deck I want to build with this feature (not in a hurry).

2024-03-03 21:57 UTC, mkobuolys commented
https://github.com/mkobuolys/flutter_deck/assets/17415795/a87fb4f0-2d4b-488b-b1be-661be0729943

It's almost there, probably coming out tomorrow. Let's keep it a secret for now 🤫

2024-03-03 23:12 UTC, chooyan-eng commented
The control looks so cool!